"""Tests for built-in example modules and workflows."""

from __future__ import annotations

from pathlib import Path

from core import ModuleManager, PipelineExecutor, WorkflowLoader


REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES_DIR = REPO_ROOT / "modules"
WORKFLOWS_DIR = REPO_ROOT / "workflows"


def test_example_modules_are_discoverable() -> None:
    manager = ModuleManager(MODULES_DIR)

    modules = manager.scan_modules()

    assert "rename-path" in modules
    assert "write-summary" in modules
    assert "create-text-file" in modules
    assert manager.warnings == []


def test_example_workflows_load_successfully() -> None:
    loader = WorkflowLoader(WORKFLOWS_DIR)

    file_workflow = loader.load("example-file-rename.yaml")
    folder_workflow = loader.load("example-folder-rename.yaml")
    none_workflow = loader.load("example-none-generate.yaml")

    assert file_workflow.mode == "file"
    assert [step.module for step in file_workflow.steps] == ["rename-path", "write-summary"]
    assert folder_workflow.mode == "folder"
    assert [step.module for step in folder_workflow.steps] == ["rename-path", "write-summary"]
    assert none_workflow.mode == "none"
    assert [step.module for step in none_workflow.steps] == [
        "create-text-file",
        "write-summary",
    ]


def test_example_file_workflow_runs_end_to_end(tmp_path: Path) -> None:
    source_file = tmp_path / "report.txt"
    source_file.write_text("demo", encoding="utf-8")

    loader = WorkflowLoader(WORKFLOWS_DIR)
    workflow = loader.load("example-file-rename.yaml")
    executor = PipelineExecutor(ModuleManager(MODULES_DIR))

    result = executor.execute(
        workflow,
        input_path=source_file,
        output_dir=tmp_path / "output",
    )

    assert result["success"] is True
    assert (tmp_path / "output" / "report_done.txt").exists()
    summary = tmp_path / "output" / "file-workflow-summary.txt"
    assert summary.exists()
    assert "working_path:" in summary.read_text(encoding="utf-8")


def test_example_folder_workflow_runs_end_to_end(tmp_path: Path) -> None:
    source_dir = tmp_path / "project"
    source_dir.mkdir()
    (source_dir / "note.txt").write_text("folder demo", encoding="utf-8")

    loader = WorkflowLoader(WORKFLOWS_DIR)
    workflow = loader.load("example-folder-rename.yaml")
    executor = PipelineExecutor(ModuleManager(MODULES_DIR))

    result = executor.execute(
        workflow,
        input_path=source_dir,
        output_dir=tmp_path / "output",
    )

    assert result["success"] is True
    renamed_dir = tmp_path / "output" / "packaged-project"
    assert renamed_dir.exists()
    assert (renamed_dir / "note.txt").exists()
    summary = tmp_path / "output" / "folder-workflow-summary.txt"
    assert summary.exists()
    assert "renamed_path:" in summary.read_text(encoding="utf-8")


def test_example_none_workflow_runs_end_to_end(tmp_path: Path) -> None:
    loader = WorkflowLoader(WORKFLOWS_DIR)
    workflow = loader.load("example-none-generate.yaml")
    executor = PipelineExecutor(ModuleManager(MODULES_DIR))

    result = executor.execute(
        workflow,
        output_dir=tmp_path / "output",
    )

    assert result["success"] is True
    generated_file = tmp_path / "output" / "generated-note.txt"
    assert generated_file.exists()
    assert generated_file.read_text(encoding="utf-8") == "generated by example none workflow"
    summary = tmp_path / "output" / "none-workflow-summary.txt"
    assert summary.exists()
    assert "created_file:" in summary.read_text(encoding="utf-8")
